"""LSV1 (LocalSecretVault version 1) binary vault format.

Binary layout:
    Magic:     4 bytes  "LSV1"
    Version:   1 byte   (0x01)
    Salt:     32 bytes  (random, for Argon2id)
    KDF time:  4 bytes  (uint32 big-endian)
    KDF mem:   4 bytes  (uint32 big-endian, in KB)
    KDF par:   4 bytes  (uint32 big-endian)
    Nonce:    12 bytes  (random, for AES-GCM)
    Payload:  variable  (encrypted JSON + GCM tag, appended by cryptography lib)
"""

from __future__ import annotations

import json
import struct
from typing import Any

from localsecretvault.crypto.cipher import NONCE_LENGTH, decrypt, encrypt
from localsecretvault.crypto.kdf import (
    SALT_LENGTH,
    KDFParams,
    derive_key,
    generate_salt,
)

MAGIC = b"LSV1"
FORMAT_VERSION = 1
SALT_SIZE = SALT_LENGTH

# Header sizes
MAGIC_SIZE = 4
VERSION_SIZE = 1
SALT_OFFSET = MAGIC_SIZE + VERSION_SIZE
KDF_TIME_OFFSET = SALT_OFFSET + SALT_SIZE
KDF_MEM_OFFSET = KDF_TIME_OFFSET + 4
KDF_PAR_OFFSET = KDF_MEM_OFFSET + 4
NONCE_OFFSET = KDF_PAR_OFFSET + 4
HEADER_SIZE = NONCE_OFFSET + NONCE_LENGTH


class VaultFormatError(Exception):
    """Raised when the vault file format is invalid."""


class VaultAuthError(Exception):
    """Raised when the master password is incorrect."""


def _encode_header(
    salt: bytes,
    time_cost: int,
    memory_cost: int,
    parallelism: int,
    nonce: bytes,
) -> bytes:
    """Encode the vault header as bytes."""
    header = bytearray()
    header.extend(MAGIC)
    header.append(FORMAT_VERSION)
    header.extend(salt)
    header.extend(struct.pack(">I", time_cost))
    header.extend(struct.pack(">I", memory_cost))
    header.extend(struct.pack(">I", parallelism))
    header.extend(nonce)
    return bytes(header)


def _parse_header(data: bytes) -> tuple[bytes, KDFParams, bytes]:
    """Parse vault header. Returns (salt, kdf_params, nonce)."""
    if len(data) < HEADER_SIZE:
        raise VaultFormatError("Vault file too short: header incomplete")

    magic = data[:MAGIC_SIZE]
    if magic != MAGIC:
        raise VaultFormatError("Not a valid vault file (invalid magic bytes)")

    version = data[MAGIC_SIZE]
    if version != FORMAT_VERSION:
        raise VaultFormatError(f"Unsupported vault format version: {version}")

    salt = data[SALT_OFFSET : SALT_OFFSET + SALT_SIZE]
    time_cost = struct.unpack(">I", data[KDF_TIME_OFFSET : KDF_TIME_OFFSET + 4])[0]
    memory_cost = struct.unpack(">I", data[KDF_MEM_OFFSET : KDF_MEM_OFFSET + 4])[0]
    parallelism = struct.unpack(">I", data[KDF_PAR_OFFSET : KDF_PAR_OFFSET + 4])[0]
    nonce = data[NONCE_OFFSET : NONCE_OFFSET + NONCE_LENGTH]

    params = KDFParams(time_cost=time_cost, memory_cost=memory_cost, parallelism=parallelism)

    return salt, params, nonce


def create_vault(password: str, data: dict[str, Any] | None = None) -> bytes:
    """Create a new encrypted vault from a password and data dict.

    Returns the complete binary vault file content.
    """
    salt = generate_salt()
    params = KDFParams()
    key = derive_key(password, salt, params)

    # The nonce inside the encrypted payload is generated by cipher.encrypt.
    # We need to parse the header to extract it for future decryption.
    # But cipher.encrypt prepends the nonce, so we encrypt, then rebuild
    # the header with the nonce from the ciphertext.
    payload = encrypt(key, json.dumps(data or {}).encode("utf-8"))

    # Extract nonce from the ciphertext (first NONCE_LENGTH bytes)
    nonce = payload[:NONCE_LENGTH]
    ciphertext = payload[NONCE_LENGTH:]

    header = _encode_header(salt, params.time_cost, params.memory_cost, params.parallelism, nonce)
    return header + ciphertext


def unlock_vault(password: str, vault_data: bytes) -> dict[str, Any]:
    """Decrypt and parse a vault.

    Returns the decrypted data dict.
    Raises VaultAuthError on wrong password.
    Raises VaultFormatError on corrupted/invalid file.
    """
    salt, params, nonce = _parse_header(vault_data)

    key = derive_key(password, salt, params)

    ciphertext = vault_data[HEADER_SIZE:]
    if not ciphertext:
        raise VaultFormatError("Vault file contains no encrypted payload")

    # Reconstruct the nonce + ciphertext format that cipher.decrypt expects
    encrypted = nonce + ciphertext

    try:
        plaintext = decrypt(key, encrypted)
    except ValueError as exc:
        if "authentication failed" in str(exc).lower():
            raise VaultAuthError("Unable to unlock vault: authentication failed.") from exc
        raise VaultFormatError(str(exc)) from exc

    try:
        return json.loads(plaintext.decode("utf-8"))
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        raise VaultFormatError("Vault payload is corrupted.") from exc


def update_vault(password: str, vault_data: bytes, new_data: dict[str, Any]) -> bytes:
    """Re-encrypt vault data with updated contents.

    Returns the complete binary vault file content.
    Raises VaultAuthError on wrong password.
    """
    salt, params, nonce = _parse_header(vault_data)

    # Verify the password first
    key = derive_key(password, salt, params)

    ciphertext = vault_data[HEADER_SIZE:]
    encrypted = nonce + ciphertext
    try:
        decrypt(key, encrypted)
    except ValueError:
        raise VaultAuthError("Unable to unlock vault: authentication failed.")

    # Re-encrypt with fresh nonce
    new_payload = encrypt(key, json.dumps(new_data).encode("utf-8"))
    new_nonce = new_payload[:NONCE_LENGTH]
    new_ciphertext = new_payload[NONCE_LENGTH:]

    header = _encode_header(salt, params.time_cost, params.memory_cost, params.parallelism, new_nonce)
    return header + new_ciphertext


def is_valid_vault(data: bytes) -> bool:
    """Check if data has valid vault format (without decrypting)."""
    try:
        if len(data) < HEADER_SIZE:
            return False
        magic = data[:MAGIC_SIZE]
        if magic != MAGIC:
            return False
        version = data[MAGIC_SIZE]
        return version == FORMAT_VERSION
    except Exception:
        return False
