"""Import and export .env files."""

from __future__ import annotations

import re
from pathlib import Path


def parse_env_file(path: Path) -> dict[str, str]:
    """Parse a .env file into a dictionary.

    Handles: comments, quoted values, empty values, whitespace.
    """
    result: dict[str, str] = {}

    if not path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    content = path.read_text(encoding="utf-8")
    for line in content.splitlines():
        line = line.strip()

        # Skip empty lines and comments
        if not line or line.startswith("#"):
            continue

        # Match KEY=VALUE patterns
        match = re.match(r'^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)', line)
        if not match:
            continue

        key = match.group(1)
        value = match.group(2).strip()

        # Handle quoted values
        if (value.startswith('"') and value.endswith('"')) or (
            value.startswith("'") and value.endswith("'")
        ):
            value = value[1:-1]
        else:
            # Remove inline comments for unquoted values
            for comment_marker in [" #", "\t#"]:
                idx = value.find(comment_marker)
                if idx >= 0:
                    value = value[:idx].strip()
                    break

        result[key] = value

    return result


def import_from_env_file(path: Path) -> list[dict[str, str]]:
    """Import a .env file and return a list of env var records.

    Each record has 'name' and 'value' keys.
    """
    env_vars = parse_env_file(path)
    return [{"name": key, "value": value} for key, value in env_vars.items()]


def export_to_env_file(
    path: Path,
    env_vars: dict[str, str],
    *,
    overwrite: bool = False,
) -> None:
    """Export environment variables to a .env file.

    Args:
        path: Destination file path.
        env_vars: Dictionary of name=value pairs.
        overwrite: If False and file exists, raises FileExistsError.
    """
    if path.exists() and not overwrite:
        raise FileExistsError(
            f"File already exists: {path}\n"
            "Use --yes to overwrite."
        )

    lines = [
        "# Generated by LocalSecretVault",
        "# WARNING: This file contains secrets in plaintext.",
        "# Do not commit this file to version control.",
        "",
    ]

    for key, value in sorted(env_vars.items()):
        # Quote values that contain special characters
        needs_quote = any(c in value for c in " \t\n\"'#$&|<>?*!~")
        if needs_quote:
            escaped = value.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'{key}="{escaped}"')
        else:
            lines.append(f"{key}={value}")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
